INSERT INTO Claim (claim_status, claim_type, created_at)
VALUES ('INCOMING', 'WRONG_DELIVERY_LOCATION', NOW(6)),
       ('INCOMING', 'DELAYED_DELIVERY', NOW(6)),
       ('INCOMING', 'MISSING_ITEM', NOW(6)),
       ('INCOMING', 'DAMAGED_ITEM', NOW(6)),
       ('INCOMING', 'WRONG_DELIVERY_LOCATION', NOW(6)),
       ('INCOMING', 'DELAYED_DELIVERY', NOW(6)),
       ('INCOMING', 'MISSING_ITEM' ,NOW(6)),
       ('INCOMING','DAMAGED_ITEM' ,NOW(6)),
       ('INCOMING','WRONG_DELIVERY_LOCATION' ,NOW(6)),
       ('INCOMING','DELAYED_DELIVERY' ,NOW(6));
